### ISSUE TITLE
CI via GitHub Actions?

### ISSUE THREAD

**Issue by robert-scheck** [RIPE-NCC/bgpdump#13]
Would you accept a CI (e.g. build using multiple compilers, maybe different operating systems, built-in selftest, maybe some code analysis) via GitHub Actions if provided via pull request? [GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration).

**Comment by spakka** [comment]
I'd certainly appreciate it! Want to check if @fobser or @ripe-gii have any objections?
And thanks for your interest in helping!

**Comment by fobser** [comment]
@spakka sounds good!

**Comment by spakka** [comment]
@robert-scheck Thanks for the submissions, sorry for the delay but I've merged those now, it is most appreciated!
