### ISSUE TITLE
Tags missing after migration from github

### ISSUE THREAD

**Issue by scpeters** [RIPE-NCC/bgpdump#3]
The 1.6.0 tag from bitbucket is used in the [homebrew-core formula for bgpdump](https://github.com/Homebrew/homebrew-core/blob/master/Formula/bgpdump.rb#L4), but I don't see that tag on this git repository.

**Comment by scpeters** [comment]
I believe the 1.6.0 tag should point to 3fe0bb23e252b48976a1784a094b75a843902163

* https://bitbucket.org/ripencc/bgpdump-hg/commits/tag/1.6.0

**Comment by spakka** [comment]
Apologies.
I have bumped a new release on Github.
You can update the Homebrew formula to point here now.

Thanks,
Colin

**Comment by scpeters** [comment]
it looks like the latest release was added to homebrew-core in https://github.com/Homebrew/homebrew-core/pull/53846

**Comment by spakka** [comment]
Closing as this is fixed now, thanks for the report.
