### ISSUE TITLE
Does bgpdump support the resolution of vpnv4, vpnv6, evpn and other address families?

### ISSUE THREAD

**Issue by angelyouyou** [RIPE-NCC/bgpdump#7]
Does bgpdump support the resolution of vpnv4, vpnv6, evpn and other address families?

**Comment by spakka** [comment]
@angelyouyou 
No, there is currently support for:
- Basic IPv4 in BGP
- MP-BGP, AFI IPv4
- MP-BGP, AFI IPv6
